source 'https://github.com/CocoaPods/Specs.git'


target 'SinchCallingUIKit_Example', :exclusive => true do
  pod "SinchCallingUIKit", :path => "../"
end

target 'SinchCallingUIKit_Tests', :exclusive => true do
  pod "SinchCallingUIKit", :path => "../"

  
end
